mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^add_question/$', views.add_question, name='add_question'),
    url(r'^(?P<question_id>[0-9]+)/add_choice/$', views.add_choice, name='add_choice'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Question, Choice


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['question_text']


class ChoicesForm(forms.ModelForm):

    class Meta:
        model = Choice
        fields = ['choice_text']

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout

from .models import Choice, Question
from .forms import UserForm, QuestionForm, ChoicesForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):

        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):

        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def login_user(request):
    form = UserForm(request.POST or None)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                questions = Question.objects.filter(user=request.user)
                return render(request, 'polls/user_page.html', {'questions': questions, 'name': user.username})
            else:
                return render(request, 'polls/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'polls/login.html', {'error_message': 'Invalid login'})
    context = {
        "form": form,
    }
    return render(request, 'polls/login.html', context)


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                own_questions = Question.objects.filter(user=request.user)
                return render(request, 'polls/user_page.html', {'question': own_questions})
    context = {
        "form": form,
    }
    return render(request, 'polls/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'polls/login.html', context)


def add_question(request):
    if not request.user.is_authenticated():
        return render(request, 'polls/add_question.html')
    else:
        form = QuestionForm(request.POST or None)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.question_text = question.question_text
            question.pub_date = timezone.now()
            question.save()
            my_questions=Question.objects.filter(user=request.user).order_by('-pub_date')

            return render(request, 'polls/user_page.html', {'questions': my_questions})
        context = {
            "form": form,
        }
        return render(request, 'polls/add_question.html', context)


def add_choice(request, question_id):
    form = ChoicesForm(request.POST or None)
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    if form.is_valid():
        for s in choices:
            if s.choice_text == form.cleaned_data.get("choice_text"):
                context = {
                    'choices': choices,
                    'question': question,
                    'form': form,
                }
                return render(request, 'polls/add_choice.html', context)
        choice = form.save(commit=False)
        choice.question = question
        choice.choice_text = choice.choice_text
        choice.save()
        my_questions = Question.objects.filter(user=request.user).order_by('-pub_date')
        return render(request, 'polls/user_page.html', {'questions': my_questions})
    context = {
        'choices': choices,
        'question': question,
        'form': form,
    }
    return render(request, 'polls/add_choice.html', context)

mysite/polls/templates/polls/add_choice.html
{% extends "polls/main_template.html" %}


{% block content %}

<h1>{{ question.question_text }} --> has the options:</h1>

</br>

<ul>
{% for choice in choices %}
     <li>{{choice.choice_text}}</li>
{% endfor %}

</ul>

<form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Add choice">

</form>

{% endblock %}

mysite/polls/templates/polls/add_question.html
{% extends "polls/main_template.html" %}

{% block title %}Adds a question{% endblock %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Add question">

  </form>

{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends "polls/main_template.html" %}

{% block title %}Details Page{% endblock %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</br>
</br>
</br>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>


{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/main_template.html" %}

{% load static %}

{% block title %}Index Page{% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:register' %}">Register</a>

</br>

<a href="{% url 'polls:login_user' %}">Sign In </a>

{% endblock %}

mysite/polls/templates/polls/login.html
 {% extends "polls/main_template.html" %}

 {% block title %}Log In{% endblock %}

 {% block content %}
   <h1>Login</h1>

   <form action="{% url 'polls:login_user'%}" method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Login">

   </form>
 {% endblock %}

mysite/polls/templates/polls/main_template.html
<! DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
   <head>

      <title>
         {% block title %}Page Title{% endblock %}
      </title>

   </head>

   <body>

      {% block content %}

      {% endblock %}

   </body>
</html>

mysite/polls/templates/polls/register.html
{% extends "polls/main_template.html" %}

{% block title %}Register{% endblock %}

{% block content %}

 <h1>Create an account</h1>

<form action="" method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create the account">

  </form>

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends "polls/main_template.html" %}

{% block title %}Results Page{% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

</br>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}

mysite/polls/templates/polls/user_page.html
{% extends "polls/main_template.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% block content %}

{% if questions %}
    <ul>
    {% for question in questions %}
        <li><a href="{% url 'polls:add_choice' question.id %}">{{ question.question_text }}</a>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:add_question' %}">Add New Question</a>

</br>

<a href="{% url 'polls:logout_user' %}">Log out</a>

{% endblock %}